apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: td-namespace
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: td-namespace
subjects:
- kind: User
  name: alice   # pour TD on peut utiliser ServiceAccount plutôt
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
