apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
spec:
  containers:
  - name: web
    image: nginx
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: demo-vol
  volumes:
    - name: demo-vol
      persistentVolumeClaim:
        claimName: pvc-demo
